### ISSUE TITLE
assertion.raises didn't returns context

### ISSUE THREAD

**Issue by akaspin** [trifonovmixail/seismograph#1]
```
Traceback (most recent call last):
  File "/Users/spin/Craft/plato/bbc/py/venv/lib/python2.7/site-packages/seismograph/case.py", line 695, in __run__
    test_method()
  File "./bloomberg/test/ping_test.py", line 41, in handler_ref_test
    with case.assertion.raises(BaseException) as ctx:
AttributeError: __exit__
```

**Comment by trifonovmixail** [comment]
Released
